template: true
valuesFilePath: ./values.yml

resources:
  - name: git_repository_resource
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      branches:
        include: {{ .Values.myRepo.branch }}

  - name: my_helm_chart
    type: HelmChart
    configuration:
      sourceArtifactory: {{ .Values.myHelmChart.artifactoryProvider }}
      repository: {{ .Values.myHelmChart.repository }}
      chart: {{ .Values.myHelmChart.chartName }}
      version: {{ .Values.myHelmChart.chartVersion }}

pipelines:
  - name: {{ .Values.myPipeline.name }}
    steps:
      - name: pre_helm_deploy
        type: Bash
        configuration:
          inputResources:
            - name: git_repository_resource
              trigger: false
        execution:
          onExecute:
            - echo "Hello JFrog Pipelines!"
            - echo $res_git_repository_resource_resourcePath

      - name: helm_deploy
        type: HelmDeploy
        configuration:
          nodePool: Ubuntu
          helmVersion: 3
          releaseName: {{ .Values.myHelmChart.releaseName }} 
          dryRun: true
          flags: "{{ .Values.myHelmChart.flags }}"
          environmentVariables:
            HELM_NAMESPACE: {{ .Values.myHelmChart.namespace }}          
          integrations:
            - name: {{ .Values.myKubernetes.integrationName }}
          inputResources:
            - name: my_helm_chart
          inputSteps:
            - name: pre_helm_deploy
